name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

     - name: Deploy via SSH (Username & Password)
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@ssh.r3dsys.com << 'EOF'
            cd ~/R3DSYS
            /home/k14/.nvm/versions/node/v22.14.0/bin/pm2 stop api
            git pull origin main
            cd js-server
            pnpm install
            cd ..
            /home/k14/.nvm/versions/node/v22.14.0/bin/pm2 restart api
          EOF

